### ISSUE TITLE
AnonGT.py problem

### ISSUE THREAD

**Issue by Kalisabbb** [gt0day/AnonGT#7]
Hello! Good work I have this tool in other computers

But I trying run in a pinephone (Linux mobile) 

And I have this :

$ sudo python3 AnonGT.py

Traceback (most recent call last):

File "/home/kali/AnonGT/AnonGT.py", line 2, in <module>

from core.config.functions import check _root, listToString, clear, exec_command, i s_started, get_user, ERROR, MSG

File "/home/kali/AnonGT/core/config/funct ions.py", line 1, in <module>

from core.config.librareis import *

File "/home/kali/AnonGT/core/config/libra

reis.py", line 2, in <module> from requests import get

ModuleNotFoundError: No module named 'reque sts'

![IMG_20241001_164030.jpg](https://github.com/user-attachments/assets/eb1a6c3d-558b-43ee-8b7d-45c72a6290b5)

Thank you

**Comment by daga5988** [comment]
I have a similar issue but it shows me with netifaces. Testing on kali-rolling 2024.3 x86_64

─$ sudo python3 ./AnonGT.py;
Traceback (most recent call last):
  File "/home/serticr/AnonGT/./AnonGT.py", line 2, in <module>
    from core.config.functions import check_root, listToString, clear, exec_command, is_started, get_user,ERROR, MSG
  File "/home/serticr/AnonGT/core/config/functions.py", line 1, in <module>
    from core.config.librareis import *
  File "/home/serticr/AnonGT/core/config/librareis.py", line 11, in <module>
    import netifaces
ModuleNotFoundError: No module named 'netifaces'

**Comment by gt0day** [comment]
First make sure run sudo python3 install.py
then any python package not found
pip3 install requests netiaces
